// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ayy63pEJowmEAXP9p2RIwG9UprokOjA',
    appId: '1:585107310878:web:dc705c7fba0ec3916de10f',
    messagingSenderId: '585107310878',
    projectId: 'saha-map',
    authDomain: 'saha-map.firebaseapp.com',
    storageBucket: 'saha-map.firebasestorage.app',
    measurementId: 'G-J60KN4FQBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bt1JAmeBi7m2uFr6Gb-wSD46iS8ojLM',
    appId: '1:585107310878:android:fc465b5ae0fba5fe6de10f',
    messagingSenderId: '585107310878',
    projectId: 'saha-map',
    storageBucket: 'saha-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIS2SpH4VKPtwIYmP2SI-0hnOVPm_Asu4',
    appId: '1:585107310878:ios:27c8e2dc647e37e56de10f',
    messagingSenderId: '585107310878',
    projectId: 'saha-map',
    storageBucket: 'saha-map.firebasestorage.app',
    iosBundleId: 'com.sahamap.sahaMap',
  );
}
